# Generated by Django 5.1.6 on 2025-03-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
