# Generated by Django 5.1.6 on 2025-03-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_listingimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
