# Generated by Django 5.1.6 on 2025-03-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_listing_is_premium"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="is_premium",
        ),
        migrations.AddField(
            model_name="listing",
            name="ad_type",
            field=models.CharField(
                choices=[("free", "Free"), ("paid", "Paid")],
                default="free",
                max_length=10,
            ),
        ),
    ]
