# Generated by Django 5.1.6 on 2025-03-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_remove_listing_is_premium_listing_ad_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
