# Generated by Django 5.1.6 on 2025-03-21 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("direct_messages", "0001_initial"),
        ("listings", "0006_remove_listing_is_premium_listing_ad_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="listings.listing",
            ),
        ),
    ]
